language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux

sudo: false

install:
  - pip install -e git+https://github.com/webrecorder/warcio.git@develop#egg=warcio-1.4.0
  - python setup.py install
  - pip install coverage pytest-cov coveralls

script:
  - python setup.py test

after_success:
  - coveralls

